"""add awrad

Revision ID: 8100a9ba8a14
Revises: 
Create Date: 2020-07-18 22:49:18.630011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8100a9ba8a14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('award',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('number', sa.String(length=10), nullable=True),
                    sa.Column('open_id', sa.String(length=50), nullable=True),
                    sa.Column('valid', sa.Boolean(), nullable=True, comment='是否为中奖号码'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('number')
                    )


def downgrade():
    op.drop_table('award')
    # ### end Alembic commands ###
